### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by jeroenpeters1986** [undeterred965/customMM#1]
Hi,

so sorry to contact you via this issue, but I didnt find any contact info. Very cool that you made your config and css available trhought Github. I made a Mini Magic Mirror (the pyramid one) myself too and your CSS gave it the right amount of font-sizes to be readable.

Do you also have issues with the MMM-Carousel that it will display all modules at once at the first time?

Thanks for sharing!!

Kind regards,

Jeroen Peters

**Comment by undeterred965** [comment]
Hi Jeroen,

That's ok. Glad that my code helped you.

MMM-Carousel displaying all modules at once? Looking at my code, I think you're right. I haven't noticed that issue with my MM but I do use an underpowered PiZero that is very slow at first displaying the screen. What version of Pi do you use?

Jon

**Comment by jeroenpeters1986** [comment]
Hi Jon,

I alsof have the PiZero (W) and once it's started, its cool. At the very start, all the widgets are shown together. I am not using slides btw, if all screens have passed, it's going OK again.
Do you use the barnaby MMM-Caroussel, or do you use your own?
Also, I built mine after seeing this video: https://www.youtube.com/watch?v=2POMz7ta9uw
I guess you did too?

Kind regards, 

Jeroen Peters

**Comment by undeterred965** [comment]
Yes, I saw the video and inspired me to build my mini version. Due to technical issues however (the 4" screen I bought not being bright enough and using all the GPIO pins) I redesigned mine to lose the mirror and gain touch-screen controls. More of a mini-magic than a mini-MM.
![mini-Magic](https://user-images.githubusercontent.com/62571573/84359875-2c63d780-abc1-11ea-848a-facaf4df4ef8.jpg)

All my code repositories on GitHub are for the mini-magic, so yes I use my own doctored MMM-Carousel. You are welcome to try it, but it is integrated with the other modules. Not good for sharing code, but then I'm a newbie to GitHub and open-source!

If you do have any issues with my MMM-Carousel, let me know. Also be interesting if you could share a pic of your mini-MM?

Cheers,
Jon

**Comment by jeroenpeters1986** [comment]
Hey Jon,

I am familiair with changing and altering the code, I made three modules during my MMM project. I think I will try your caroussel. I surely will post pictures of mine, but I have to make a few first haha :-)

**Comment by jeroenpeters1986** [comment]
Hey Jon,
here is a small collection of my project. I accidentally forget to alter the color of the 3D print I ordered, but it worked out OK. The mirror is not attached at this moment, because it fell off after a few days.
![miniMagicMirror](https://jeroenpeters.dev/wp-content/uploads/2020/06/mmpi0.png)
The mirror is actually a piece of cut glass, with some mirror-foil behind it.

**Comment by undeterred965** [comment]
The case is cool! Much cleaner design than mine.

Cheers,
Jon

**Comment by jeroenpeters1986** [comment]
Thanks so much Jon. It's the 3dprint of thingiverse that the author of the
movie published. I just ordered it at a print-shop here in the Netherland
